package fi.polar.polarmathsmart.trainingbenefit;

public enum TrainingFeedback {
   BASIC_AND_STEADY_STATE_TRAINING,
   BASIC_AND_STEADY_STATE_TRAINING_LONG,
   BASIC_TRAINING,
   BASIC_TRAINING_LONG,
   MAXIMUM_AND_TEMPO_TRAINING,
   MAXIMUM_TRAINING,
   MAXIMUM_TRAINING_PLUS,
   NONE,
   RECOVERY_TRAINING,
   STEADY_STATE_AND_BASIC_TRAINING,
   STEADY_STATE_AND_BASIC_TRAINING_LONG,
   STEADY_STATE_AND_TEMPO_TRAINING,
   STEADY_STATE_TRAINING,
   STEADY_STATE_TRAINING_PLUS,
   TEMPO_AND_MAXIMUM_TRAINING,
   TEMPO_AND_STEADY_STATE_TRAINING,
   TEMPO_TRAINING,
   TEMPO_TRAINING_PLUS;
}
